-- Migración para el Módulo de Liquidaciones
-- Crea la tabla de liquidaciones, vista detallada, función RPC, bucket de almacenamiento y políticas de RLS.

-- 1. Crear tabla de liquidaciones
CREATE TABLE IF NOT EXISTS public.liquidaciones (
    liquidacion_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cotizacion_id bigint REFERENCES public.cotizaciones(cotizacion_id) ON DELETE CASCADE UNIQUE,
    estado_pago text NOT NULL DEFAULT 'unpaid' CHECK (estado_pago IN ('paid', 'unpaid', 'partial')),
    monto_total numeric NOT NULL,
    fecha_liquidacion timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    fecha_pago timestamp with time zone,
    metodo_pago text,
    comprobante_pago text,
    comprobante_url text,
    notas text,
    creado_por uuid REFERENCES auth.users(id)
);

-- 2. Habilitar RLS
ALTER TABLE public.liquidaciones ENABLE ROW LEVEL SECURITY;

-- 3. Crear Políticas de RLS
CREATE POLICY liquidaciones_select_policy ON public.liquidaciones
    FOR SELECT USING ((SELECT check_permission('quotes.view')));

CREATE POLICY liquidaciones_insert_policy ON public.liquidaciones
    FOR INSERT WITH CHECK ((SELECT check_permission('quotes.approve')) AND (creado_por = auth.uid()));

CREATE POLICY liquidaciones_update_policy ON public.liquidaciones
    FOR UPDATE USING ((SELECT check_permission('quotes.approve')));

CREATE POLICY liquidaciones_delete_policy ON public.liquidaciones
    FOR DELETE USING ((SELECT check_permission('quotes.delete')));

-- 4. Crear Vista Detallada de Liquidaciones
CREATE OR REPLACE VIEW public.v_liquidaciones_detalles 
WITH (security_invoker = true)
AS
SELECT 
    l.liquidacion_id,
    l.cotizacion_id,
    l.estado_pago,
    l.monto_total,
    l.fecha_liquidacion,
    l.fecha_pago,
    l.metodo_pago,
    l.comprobante_pago,
    l.comprobante_url,
    l.notas,
    l.creado_por,
    q.codigo_referencia,
    q.moneda,
    q.nombre_grupo,
    q.cantidad_pax,
    c.nombre_completo AS cliente_nombre,
    c.email AS cliente_email,
    c.empresa AS cliente_empresa
FROM public.liquidaciones l
LEFT JOIN public.cotizaciones q ON l.cotizacion_id = q.cotizacion_id
LEFT JOIN public.clientes c ON q.cliente_id = c.cliente_id;

COMMENT ON VIEW public.v_liquidaciones_detalles IS 'Vista detallada de liquidaciones uniendo datos de cotizaciones y clientes.';

-- 5. Crear Función de Base de Datos para Liquidar Cotizaciones de forma atómica
CREATE OR REPLACE FUNCTION public.liquidar_cotizacion(p_cotizacion_id bigint, p_usuario_id uuid)
RETURNS bigint AS $$
DECLARE
  v_total numeric;
  v_liquidacion_id bigint;
BEGIN
  -- Obtener el total general de la cotización
  SELECT total_general INTO v_total FROM public.cotizaciones WHERE cotizacion_id = p_cotizacion_id;
  
  -- Actualizar el estado de la cotización a 'Liquidated'
  UPDATE public.cotizaciones 
  SET estado = 'Liquidated'
  WHERE cotizacion_id = p_cotizacion_id;
  
  -- Insertar la nueva liquidación asociada
  INSERT INTO public.liquidaciones (cotizacion_id, estado_pago, monto_total, creado_por, fecha_liquidacion)
  VALUES (p_cotizacion_id, 'unpaid', v_total, p_usuario_id, now())
  RETURNING liquidacion_id INTO v_liquidacion_id;
  
  RETURN v_liquidacion_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. Configurar Bucket de Almacenamiento para Comprobantes de Pago
INSERT INTO storage.buckets (id, name, public)
VALUES ('comprobantes', 'comprobantes', true)
ON CONFLICT (id) DO NOTHING;

-- Crear políticas para el bucket de comprobantes
CREATE POLICY "Comprobantes public access" ON storage.objects
    FOR SELECT USING (bucket_id = 'comprobantes');

CREATE POLICY "Comprobantes upload policy" ON storage.objects
    FOR INSERT WITH CHECK (bucket_id = 'comprobantes' AND auth.role() = 'authenticated');

CREATE POLICY "Comprobantes update policy" ON storage.objects
    FOR UPDATE USING (bucket_id = 'comprobantes' AND auth.role() = 'authenticated');

CREATE POLICY "Comprobantes delete policy" ON storage.objects
    FOR DELETE USING (bucket_id = 'comprobantes' AND auth.role() = 'authenticated');

-- 7. Migración de Datos Históricos
-- Migrar cotizaciones Aprobadas
INSERT INTO public.liquidaciones (cotizacion_id, estado_pago, monto_total, creado_por, fecha_liquidacion)
SELECT cotizacion_id, 'unpaid', total_general, creado_por, COALESCE(fecha_aprobacion, fecha_creacion, now())
FROM public.cotizaciones
WHERE estado = 'Approved'
ON CONFLICT (cotizacion_id) DO NOTHING;

UPDATE public.cotizaciones
SET estado = 'Liquidated'
WHERE estado = 'Approved';

-- Migrar cotizaciones Vendidas
INSERT INTO public.liquidaciones (cotizacion_id, estado_pago, monto_total, creado_por, fecha_liquidacion, fecha_pago)
SELECT cotizacion_id, 'paid', total_general, creado_por, COALESCE(fecha_aprobacion, fecha_creacion, now()), COALESCE(fecha_aprobacion, fecha_creacion, now())
FROM public.cotizaciones
WHERE estado = 'Sold'
ON CONFLICT (cotizacion_id) DO NOTHING;

UPDATE public.cotizaciones
SET estado = 'Liquidated'
WHERE estado = 'Sold';
