-- Migración para permitir la edición y reversión justificada de pagos en liquidaciones
-- Crea la tabla de modificaciones de liquidaciones y las funciones RPC para revertir y editar pagos.

-- 1. Crear tabla de historial de modificaciones de liquidaciones
CREATE TABLE IF NOT EXISTS public.modificaciones_liquidaciones (
    modificacion_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    liquidacion_id bigint REFERENCES public.liquidaciones(liquidacion_id) ON DELETE CASCADE,
    tipo_modificacion text NOT NULL CHECK (tipo_modificacion IN ('edit_payment', 'revert_payment')),
    justificacion text NOT NULL,
    creado_por uuid REFERENCES public.profiles(profile_id) ON DELETE SET NULL,
    fecha_modificacion timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    valores_anteriores jsonb,
    valores_nuevos jsonb
);

-- 2. Habilitar RLS y políticas
ALTER TABLE public.modificaciones_liquidaciones ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS modificaciones_liq_select_policy ON public.modificaciones_liquidaciones;
CREATE POLICY modificaciones_liq_select_policy ON public.modificaciones_liquidaciones
    FOR SELECT TO authenticated USING (check_permission('quotes.view'));

DROP POLICY IF EXISTS modificaciones_liq_insert_policy ON public.modificaciones_liquidaciones;
CREATE POLICY modificaciones_liq_insert_policy ON public.modificaciones_liquidaciones
    FOR INSERT TO authenticated WITH CHECK (check_permission('quotes.approve') AND (creado_por = auth.uid()));

GRANT SELECT, INSERT ON public.modificaciones_liquidaciones TO authenticated;

-- 3. Función RPC para Revertir Pago (Marcar como No Pagado)
CREATE OR REPLACE FUNCTION public.revertir_pago_liquidacion(
    p_liquidacion_id bigint, 
    p_justificacion text, 
    p_usuario_id uuid
) RETURNS void 
LANGUAGE plpgsql 
SECURITY DEFINER
AS $$
DECLARE
  v_valores_anteriores jsonb;
BEGIN
  -- Verificar permisos
  IF NOT public.check_permission('quotes.approve') THEN
    RAISE EXCEPTION 'No tiene permisos para modificar pagos de liquidación';
  END IF;
  
  -- Obtener valores actuales
  SELECT to_jsonb(l) INTO v_valores_anteriores 
  FROM public.liquidaciones l 
  WHERE l.liquidacion_id = p_liquidacion_id;

  -- Registrar la justificación
  INSERT INTO public.modificaciones_liquidaciones (
      liquidacion_id, 
      tipo_modificacion, 
      justificacion, 
      creado_por, 
      valores_anteriores, 
      valores_nuevos
  )
  VALUES (
      p_liquidacion_id, 
      'revert_payment', 
      p_justificacion, 
      p_usuario_id, 
      v_valores_anteriores, 
      '{"estado_pago": "unpaid"}'::jsonb
  );

  -- Actualizar liquidación
  UPDATE public.liquidaciones 
  SET estado_pago = 'unpaid',
      fecha_pago = NULL,
      metodo_pago = NULL,
      comprobante_pago = NULL,
      comprobante_url = NULL,
      notas = NULL
  WHERE liquidacion_id = p_liquidacion_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.revertir_pago_liquidacion(bigint, text, uuid) TO authenticated;

-- 4. Función RPC para Editar/Corregir Pago Existente
CREATE OR REPLACE FUNCTION public.editar_pago_liquidacion(
    p_liquidacion_id bigint, 
    p_metodo_pago text,
    p_comprobante_pago text,
    p_comprobante_url text,
    p_notas text,
    p_justificacion text, 
    p_usuario_id uuid
) RETURNS void 
LANGUAGE plpgsql 
SECURITY DEFINER
AS $$
DECLARE
  v_valores_anteriores jsonb;
  v_valores_nuevos jsonb;
BEGIN
  -- Verificar permisos
  IF NOT public.check_permission('quotes.approve') THEN
    RAISE EXCEPTION 'No tiene permisos para modificar pagos de liquidación';
  END IF;

  -- Obtener valores actuales
  SELECT to_jsonb(l) INTO v_valores_anteriores 
  FROM public.liquidaciones l 
  WHERE l.liquidacion_id = p_liquidacion_id;

  -- Actualizar liquidación
  UPDATE public.liquidaciones 
  SET metodo_pago = p_metodo_pago,
      comprobante_pago = p_comprobante_pago,
      comprobante_url = NULLIF(p_comprobante_url, ''),
      notas = NULLIF(p_notas, ''),
      fecha_pago = now()
  WHERE liquidacion_id = p_liquidacion_id;

  -- Obtener valores actualizados
  SELECT to_jsonb(l) INTO v_valores_nuevos 
  FROM public.liquidaciones l 
  WHERE l.liquidacion_id = p_liquidacion_id;

  -- Registrar justificación
  INSERT INTO public.modificaciones_liquidaciones (
      liquidacion_id, 
      tipo_modificacion, 
      justificacion, 
      creado_por, 
      valores_anteriores, 
      valores_nuevos
  )
  VALUES (
      p_liquidacion_id, 
      'edit_payment', 
      p_justificacion, 
      p_usuario_id, 
      v_valores_anteriores, 
      v_valores_nuevos
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.editar_pago_liquidacion(bigint, text, text, text, text, text, uuid) TO authenticated;
