-- Migración para permitir la reapertura de cotizaciones/liquidaciones por administradores
-- Registra el nuevo permiso, la tabla de reaperturas, y actualiza las funciones de liquidación y reapertura.

-- 1. Registrar permiso de reapertura
INSERT INTO public.permissions (code, description, module)
VALUES ('quotes.reopen', 'Reabrir cotizaciones liquidadas o pagadas para edición', 'quotes')
ON CONFLICT (code) DO NOTHING;

-- 2. Asignar el permiso al rol 'admin'
INSERT INTO public.role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM public.roles r, public.permissions p
WHERE r.name = 'admin' AND p.code = 'quotes.reopen'
ON CONFLICT DO NOTHING;

-- 3. Sincronizar claims para usuarios administradores actuales
DO $$
DECLARE
  v_user_id uuid;
BEGIN
  FOR v_user_id IN (
    SELECT ur.user_id 
    FROM public.user_roles ur
    JOIN public.roles r ON ur.role_id = r.id
    WHERE r.name = 'admin'
  ) LOOP
    PERFORM public.fn_sync_user_claims(v_user_id);
  END LOOP;
END;
$$;

-- 4. Crear tabla de historial de reaperturas
CREATE TABLE IF NOT EXISTS public.reaperturas_cotizaciones (
    reapertura_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cotizacion_id bigint REFERENCES public.cotizaciones(cotizacion_id) ON DELETE CASCADE,
    justificacion text NOT NULL,
    creado_por uuid REFERENCES public.profiles(profile_id) ON DELETE SET NULL,
    fecha_reapertura timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    monto_anterior numeric NOT NULL,
    estado_pago_anterior text NOT NULL
);

-- 5. Habilitar RLS y políticas
ALTER TABLE public.reaperturas_cotizaciones ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS reaperturas_select_policy ON public.reaperturas_cotizaciones;
CREATE POLICY reaperturas_select_policy ON public.reaperturas_cotizaciones
    FOR SELECT TO authenticated USING (check_permission('quotes.view'));

DROP POLICY IF EXISTS reaperturas_insert_policy ON public.reaperturas_cotizaciones;
CREATE POLICY reaperturas_insert_policy ON public.reaperturas_cotizaciones
    FOR INSERT TO authenticated WITH CHECK (check_permission('quotes.reopen') AND (creado_por = auth.uid()));

GRANT SELECT, INSERT ON public.reaperturas_cotizaciones TO authenticated;

-- 6. Crear Función RPC para Reabrir Cotización de manera atómica
CREATE OR REPLACE FUNCTION public.reabrir_cotizacion(
    p_cotizacion_id bigint, 
    p_justificacion text, 
    p_usuario_id uuid
) RETURNS void 
LANGUAGE plpgsql 
SECURITY DEFINER
AS $$
DECLARE
  v_monto_anterior numeric;
  v_estado_pago_anterior text;
BEGIN
  -- Validar permisos del ejecutor
  IF NOT public.check_permission('quotes.reopen') THEN
    RAISE EXCEPTION 'No tiene permisos para reabrir cotizaciones';
  END IF;

  -- Obtener valores actuales de la cotización y liquidación
  SELECT total_general INTO v_monto_anterior FROM public.cotizaciones WHERE cotizacion_id = p_cotizacion_id;
  SELECT estado_pago INTO v_estado_pago_anterior FROM public.liquidaciones WHERE cotizacion_id = p_cotizacion_id;

  -- Insertar registro de historial
  INSERT INTO public.reaperturas_cotizaciones (cotizacion_id, justificacion, creado_por, monto_anterior, estado_pago_anterior)
  VALUES (p_cotizacion_id, p_justificacion, p_usuario_id, v_monto_anterior, COALESCE(v_estado_pago_anterior, 'unpaid'));

  -- Cambiar el estado de la cotización de vuelta a 'Draft'
  UPDATE public.cotizaciones 
  SET estado = 'Draft'
  WHERE cotizacion_id = p_cotizacion_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.reabrir_cotizacion(bigint, text, uuid) TO authenticated;

-- 7. Actualizar la función liquidar_cotizacion para manejar ON CONFLICT
CREATE OR REPLACE FUNCTION public.liquidar_cotizacion(p_cotizacion_id bigint, p_usuario_id uuid)
RETURNS bigint AS $$
DECLARE
  v_total numeric;
  v_liquidacion_id bigint;
BEGIN
  -- Obtener el total general de la cotización
  SELECT total_general INTO v_total FROM public.cotizaciones WHERE cotizacion_id = p_cotizacion_id;
  
  -- Actualizar el estado de la cotización a 'Liquidated'
  UPDATE public.cotizaciones 
  SET estado = 'Liquidated'
  WHERE cotizacion_id = p_cotizacion_id;
  
  -- Insertar o actualizar la liquidación asociada
  INSERT INTO public.liquidaciones (cotizacion_id, estado_pago, monto_total, creado_por, fecha_liquidacion)
  VALUES (p_cotizacion_id, 'unpaid', v_total, p_usuario_id, now())
  ON CONFLICT (cotizacion_id) DO UPDATE 
  SET estado_pago = CASE 
        WHEN liquidaciones.estado_pago = 'paid' AND v_total > liquidaciones.monto_total THEN 'partial'::text
        ELSE liquidaciones.estado_pago 
      END,
      monto_total = EXCLUDED.monto_total,
      creado_por = EXCLUDED.creado_por,
      fecha_liquidacion = now()
  RETURNING liquidacion_id INTO v_liquidacion_id;
  
  RETURN v_liquidacion_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 8. Crear trigger de seguridad antes de update en cotizaciones para bloquear reabiertos manuales sin permiso
CREATE OR REPLACE FUNCTION public.fn_prevent_unauthorized_reopen()
RETURNS trigger 
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Si el estado cambia de Liquidated a cualquier otro estado
  IF OLD.estado = 'Liquidated' AND NEW.estado != 'Liquidated' THEN
    IF NOT public.check_permission('quotes.reopen') THEN
      RAISE EXCEPTION 'No está autorizado a cambiar el estado de una cotización liquidada';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_prevent_unauthorized_reopen ON public.cotizaciones;
CREATE TRIGGER trg_prevent_unauthorized_reopen
    BEFORE UPDATE ON public.cotizaciones
    FOR EACH ROW
    EXECUTE FUNCTION public.fn_prevent_unauthorized_reopen();
